#!/bin/bash
reserved=("master develop staging")
IFS='
'
for line in `git branch --format='%(refname:short)'`; do
    if [[ $line == *$in* ]]; then
        if [[ ! " ${reserved[@]} " =~ "$line " ]]; then
            git branch -D $line
        fi
    fi
done
