#!/bin/bash
gnome-terminal \
   --tab -t 'Git: Explorer' --working-directory="$HOME/Documents/work/explorer" \
   --tab -t 'Git: Plugins' --working-directory="$HOME/Documents/work/explorer-plugins" \
   --tab -t 'Git: Terra' --working-directory="$HOME/Documents/work/terra/terra-java" \
   --tab -t 'Git: Rest' --working-directory="$HOME/Documents/work/"
